version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    # Add your key.json to backend/ directory

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
